library(Seurat)
library(SeuratDisk)
library(SeuratData)
obj <- readRDS("obj.RDS")
SaveH5Seurat(obj, filename = "obj.h5Seurat", overwrite = TRUE)
Convert("obj.h5Seurat", dest = "h5ad", overwrite = TRUE)
